version: '3'
services:

  # Nginx client server
  nginx-client:
    container_name: nginx-client
    build:
        context: ./docker/nginx-client
        dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 28874:3000
    volumes:
        - ./client:/var/www
    networks:
      - app-network


  # MySQL server for the server side app
  mysql-server:
    image: mysql:5.7.22
    container_name: mysql-server
    restart: unless-stopped
    tty: true
    ports:
      - "16427:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: CcS2GMaacE7Kh8Gj4NJ5VF1
      MYSQL_DATABASE: iremember
    volumes:
      - ./docker/mysql-server/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network


  # Nginx server for the server side app
  nginx-server:
    container_name: nginx-server
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 49691:80
    volumes:
      - ./docker/nginx-server/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./server:/var/www
    networks:
      - app-network


  # PHP server for the server side app
  php-server:
    build:
      context: ./docker/php-server
      dockerfile: Dockerfile
    container_name: php-server
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./server:/var/www
      - ./docker/php-server/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - mysql-server


# Networks
networks:
  app-network:
    driver: bridge